### ISSUE TITLE
Using sqlanydb with Python 3.6.1 on Win 32

### ISSUE THREAD

**Issue by kennb** [sqlanywhere/sqlanydb#10]

**Comment by kennb** [comment]
When I run a simple test script using the above library on Python 2.7 on Windows it works perfectly. However, if I do exactly the same thing on Python 3.6 on Windows I get the result below.

Is there something important we are missing?


C:\Sybase\IQ-15_4\SDK\Python\Scripts>python bktest.py
Traceback (most recent call last):
  File "C:\Users\kennb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlanydb.py", line 419, in __init__
    context = self.api.sqlany_init_ex(name, API_VERSION_EX, byref(ver))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bktest.py", line 20, in <module>
    import sqlanydb
  File "C:\Users\kennb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlanydb.py", line 451, in <module>
    class Connection(object):
  File "C:\Users\kennb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlanydb.py", line 453, in Connection
    def __init__(self, args, kwargs, parent = Root("PYTHON")):
  File "C:\Users\kennb\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sqlanydb.py", line 430, in __init__
    if (not self.api.sqlany_init(name, API_VERSION, byref(ver)) or
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

**Comment by gperrow-SAP** [comment]
Can you post a script that shows the problem? If you prefer, you can email it to me at MyFirstName.MyLastName @ sap.com.
