### ISSUE TITLE
Erro after run setup.py

### ISSUE THREAD

**Issue by deniscsz** [sqlanywhere/sqlanydb#2]
sqlanydb needs some other lib to run?

Traceback (most recent call last):
  File "/home/<user_home>/test.py", line 1, in <module>
    import sqlanydb
  File "build/bdist.linux-x86_64/egg/sqlanydb.py", line 469, in <module>
  File "build/bdist.linux-x86_64/egg/sqlanydb.py", line 471, in Connection
  File "build/bdist.linux-x86_64/egg/sqlanydb.py", line 422, in **init**
  File "build/bdist.linux-x86_64/egg/sqlanydb.py", line 416, in load_library
sqlanydb.InterfaceError: Could not load dbcapi.  Tried: dbcapi.dll,libdbcapi_r.so,libdbcapi_r.dylib
Exception AttributeError: "'Root' object has no attribute 'api'" in <bound method Root.__del__ of <sqlanydb.Root object at 0x7f9a633ea6d0>> ignored

**Comment by efarrar** [comment]
Yes, you will need the SQL Anywhere Client Libraries (dbcapi). You can download them for free from http://scn.sap.com/docs/DOC-35857. This project loads the library and wraps it in a Python interface. 

If you have a full SQL Anywhere install on the machine, that will also work,

I noticed this is not mentioned in the project README. This should be updated.
